config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, length: {minimum: 5}
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :new, :edit, :destroy]
  before_action :is_owner, only: [:edit, :destroy]

  def index
    @posts = Post.all.order("created_at DESC")
  end
  def show

  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: "Foi postado com sucesso"
    else
      render "new"
    end
  end

  def edit

  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Foi alterado com sucesso"
    else
      render "edit"
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "O post foi deletado com sucesso"
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :user)
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def is_owner
    unless current_user == @post.user
      flash[:alert] = "Este post não pertence a você"
      redirect_to @post
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.haml
!!! 5
%head
  %title 
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "UnB Caronas", root_path
      %ul.nav.navbar-nav.navbar-right
        -if user_signed_in?
          %li= link_to "Nova Carona", new_post_path
          %li= link_to "Sair da Conta", destroy_user_session_path, method: :delete
        -else
          %li= link_to "Entrar na Conta", new_user_session_path
          %li= link_to "Criar Conta", new_user_registration_path

  .container
    -flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-sucess"
    = yield

app/views/posts/_form.html.haml
.form
  = simple_form_for(@post, html: { class: 'form-horizontal' }) do |f|
    = f.input :title
    %h5 Aqui você deve inserir o nome, o telefone e a quantidade de lugares disponíveis no veiculo.
    = f.input :body
    = f.button :submit

app/views/posts/edit.html.haml
%h1 Editar dados:
= render "form"
%small= link_to "Cancelar", post_path(@post)

app/views/posts/index.html.haml
%h1 Caronas Disponíveis:
- @posts.each do |post|
  .post
    %h1= link_to post.title, post

app/views/posts/new.html.haml
%h1 Inserir dados:
%h5 Aqui você deve colocar o seu local de partida e o destino final.
= render "form"
%small= link_to "Cancelar", root_path

app/views/posts/show.html.haml
.content
  %br
  %h6 Rota:
  %h1= @post.title
  %hr
  %h6 Dados da carona:
  %p= @post.body
  %h8 O usuario que postou foi: 
  %small= @post.user.email
  %br
  %small= link_to "Voltar", root_path
  -if current_user == @post.user
    %small= link_to "Editar", edit_post_path(@post)
    %small= link_to "Deletar", @post, method: :delete, data: { confirmar: "Você tem certeza?"}